### ISSUE TITLE
Can the bot use app passwords instead? 

### ISSUE THREAD

**Issue by stevevance** [MisterClean/ChicagoYIMBYblueskybot#1]
I can't find any documentation about whether the app password works the same as a regular password (but provides the app fewer permissions than if the app had the regular password).

**Comment by MisterClean** [comment]
This archived repo says that app passwords are intended for third party clients and they limit permissions so those clients can't delete your account

https://github.com/bluesky-social/atproto-ecosystem/blob/main/app-passwords.md

**Comment by MisterClean** [comment]
I successfully used an App Password
